apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-app # Mudei aqui
  template:
    metadata:
      labels:
        app: n8n-app # Mudei aqui
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        env:
        - name: N8N_PORT # <--- ADICIONE ISSO PARA FORÇAR A PORTA
          value: "5678"
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: postgres.database.svc.cluster.local
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - name: DB_POSTGRESDB_USER
          value: postgres
        - name: DB_POSTGRESDB_PASSWORD
          value: MonsterPassword2026
        - name: N8N_SECURE_COOKIE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service # Mudei o nome para não dar conflito com a variável N8N_PORT
  namespace: n8n
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: n8n-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
spec:
  ingressClassName: nginx
  rules:
  - host: n8n.127.0.0.1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-service # Nome atualizado
            port:
              number: 80