apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
spec:
  project: default
  source:
    chart: zabbix
    repoURL: https://zabbix.github.io/zabbix-helm-chrt
    targetRevision: 1.0.0
    helm:
      values: |
        zabbixServer:
          dbType: postgresql
          env:
            - name: DB_SERVER_HOST
              value: "postgres.database.svc.cluster.local"
            - name: POSTGRES_DB
              value: "zabbix"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "MonsterPassword2026"
        zabbixWeb:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: zabbix.127.0.0.1.sslip.io
  destination: # <--- ADICIONADO: ONDE O APP VAI MORAR
    server: https://kubernetes.default.svc
    namespace: zabbix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true