apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: argocd
spec:
  project: default
  source:
    chart: zabbix-helm-chrt
    repoURL: https://zabbix.github.io/zabbix-kubernetes-helm
    targetRevision: 1.3.4
    helm:
      values: |
        zabbixServer:
          dbType: postgresql
          env:
            - name: DB_SERVER_HOST
              value: "postgres.database.svc.cluster.local"
            - name: POSTGRES_DB